import { FiImage } from "react-icons/fi";
import client from 'part:@sanity/base/client'
import slugify from "../utils/slugify";

export default {
  title: "Offers",
  name: "offers",
  type: "document",
  __experimental_actions: ["update", "create", "delete", "publish"],
  fields: [
    {
      title: "Title",
      name: "title",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      title: "Order Rank",
      name: "orderRank",
      type: "string",
      hidden: true,
    },
    {
      title: "Mobile Hero Image",
      name: "mobileHeroImage",
      type: "defaultImage",
      validation: (Rule) => Rule.required(),
    },
    {
      title: "Address",
      name: "address",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      title: "Intro Text",
      name: "introText",
      type: "text",
      rows: 4
    },
    {
      title: "Content",
      name: "content",
      type: "contentSimple",
    },
    {
      title: "Show on website",
      name: "showOnWebsite",
      type: "boolean",
      description: "Check this box to make this event visible on the live website.",
      // Sets the default value to "checked" for new events
      initialValue: true,
    },
    {
      title: "Ticket URL",
      name: "ticketUrl",
      type: "url",
      description: "Deep-link URL to the app (e.g., https://nottingham.loqiva.com/public/service/redirect?type=offer&id=12345)",
    },
    {
      name: "slug",
      type: "slug",
      title: "Slug",
      description:
        'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          let titleSlug = "";
          let campaignSlug = "";
          if (doc.title) {
            titleSlug = `${doc.title}`;
          } else {
            titleSlug = "";
          }

          if (doc.campaignTitle) {
            campaignSlug = `-${doc.campaignTitle}`;
          } else {
            campaignSlug = "";
          }

          return `${titleSlug}${campaignSlug}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`),
      },
      validation: (Rule) => Rule.required().custom(async (slug, context) => {
        if (!slug?.current) return true
        const {document} = context
        const id = document._id.replace(/^drafts\./, '')
        const params = {
          draft: `drafts.${id}`,
          published: id,
          slug: slug.current
        }
        const query = `*[_type == "offers" && slug.current == $slug && !(_id in [$draft, $published])]`
        const result = await client.fetch(query, params)
        return result.length > 0 ? 'This slug is already in use' : true
      }),
    },
    {
      title: "SEO / Share Settings",
      name: "seo",
      type: "seo",
    },
  ],
  preview: {
    select: {
      title: "title",
    },
    prepare({ title }) {
      return {
        title,
      };
    },
  },
};
