import { FiImage } from "react-icons/fi";
import slugify from "../utils/slugify";

export default {
  title: "Offers",
  name: "offers",
  type: "document",
  __experimental_actions: ["update", "create", "delete", "publish"],
  fields: [
    {
      title: "Title",
      name: "title",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      title: "Order Rank",
      name: "orderRank",
      type: "string",
      hidden: true,
    },
    {
      title: "Mobile Hero Image",
      name: "mobileHeroImage",
      type: "defaultImage",
      validation: (Rule) => Rule.required(),
    },
    {
      title: "Address",
      name: "address",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      title: "Intro Text",
      name: "introText",
      type: "text",
      rows: 4
    },
    {
      title: "Content",
      name: "content",
      type: "contentSimple",
    },
    {
      name: "slug",
      type: "slug",
      title: "Slug",
      description:
        'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          let titleSlug = "";
          let campaignSlug = "";
          if (doc.title) {
            titleSlug = `${doc.title}`;
          } else {
            titleSlug = "";
          }

          if (doc.campaignTitle) {
            campaignSlug = `-${doc.campaignTitle}`;
          } else {
            campaignSlug = "";
          }

          return `${titleSlug}${campaignSlug}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`),
      },
      validation: (Rule) => Rule.required(),
    },
    {
      title: "SEO / Share Settings",
      name: "seo",
      type: "seo",
    },
  ],
  preview: {
    select: {
      title: "title",
    },
    prepare({ title }) {
      return {
        title,
      };
    },
  },
};
