import client from 'part:@sanity/base/client'
import slugify from '../utils/slugify'

export default {
    name: 'syncEvent',
    title: 'Synced Event',
    type: 'document',
    fields: [
        {
            title: "Title",
            name: "title",
            type: "string",
            validation: (Rule) => Rule.required(),
          },
          {
            title: "Order Rank",
            name: "orderRank",
            type: "string",
            hidden: true,
          },
          {
            title: "Mobile Hero Image",
            name: "mobileHeroImage",
            type: "defaultImage",
          },
          {
            title: "Featured Image",
            name: "featuredImage",
            type: "string",
            description: "Default image for this event",
          },
          {
            title: "Large Image",
            name: "largeImage",
            type: "string",
            description: "Large image URL from API (if available). This will be used in preference to the featured image when available.",
          },
          {
            title: "External ID",
            name: "externalId",
            type: "string",
            description: "ID from the external sync source",
          },
          {
            title: "Deleted",
            name: "deleted",
            type: "boolean",
            description: "Mark this event as deleted from the external source (Loqiva). Deleted events won't appear on the website.",
            initialValue: false,
          },
          {
            title: "Recurring Event ID",
            name: "recurringEventId",
            type: "string",
            description: "ID of the parent recurring event series (if this is part of a recurring series)",
          },
          {
            title: "Event Instance ID",
            name: "eventInstanceId",
            type: "string",
            description: "Unique ID for this specific instance within a recurring series",
          },
          {
            title: "Address",
            name: "address",
            type: "string",
            description: "Add the address for this event",
      
            validation: (Rule) => Rule.required(),
          },
          {
            title: "Age limit",
            name: "age",
            type: "string",
            description: "Age limit for this event",
          },
          {
            title: "Date & Time",
            name: "dateTime",
            type: "datetime",
            options: {
              dateFormat: "DD-MM-YYYY",
              timeFormat: "HH:mm",
              calendarTodayLabel: "Today",
            },
            description: "Date & Time of the event.",
      
            validation: (Rule) => Rule.required(),
          },
          {
            title: "Intro Text",
            name: "introText",
            type: "text",
            rows: 4,
            description: "This should be a short description of the event.",
          },
          {
            title: "Main content",
            name: "content",
            type: "contentSimple",
            description: "This should be the main article for the event.",
          },
          {
            title: "Show on carousel",
            name: "showOnWebsite",
            type: "boolean",
            description: "Check this box to make this event visible on the events carousel.",
            // Sets the default value to "checked" for new events
            initialValue: true,
          },
         {
            title: "Button Text",
            name: "buttonText",
            type: "string",
            description: "type the text for the button that links to the ticket URL (defaults to 'View in app' if left empty)",
            initialValue: "View in app",
          },
          {
            title: "Ticket URL",
            name: "ticketUrl",
            type: "string",
            description: "Add the ticket URL",
            validation: (Rule) => Rule.required(),
          },
          {
            name: "slug",
            type: "slug",
            title: "Slug",
            description:
              'This is required for page routing and can be auto-generated by pressing "generate"',
            options: {
              source: (doc) => {
                let titleSlug = "";
                let campaignSlug = "";
                if (doc.title) {
                  titleSlug = `${doc.title}`;
                } else {
                  titleSlug = "";
                }
      
                if (doc.campaignTitle) {
                  campaignSlug = `-${doc.campaignTitle}`;
                } else {
                  campaignSlug = "";
                }
      
                return `${titleSlug}${campaignSlug}`;
              },
              maxLength: 96,
              slugify: (input) => slugify(`${input}`),
            },
            validation: (Rule) => Rule.required().custom(async (slug, context) => {
              if (!slug?.current) return true
              const {document} = context
              const id = document._id.replace(/^drafts\./, '')
              const params = {
                draft: `drafts.${id}`,
                published: id,
                slug: slug.current
              }
              const query = `*[_type == "syncEvent" && slug.current == $slug && !(_id in [$draft, $published])]`
              const result = await client.fetch(query, params)
              return result.length > 0 ? 'This slug is already in use' : true
            }),
          },
          {
            title: "SEO / Share Settings",
            name: "seo",
            type: "seo",
          },
    ],
  }
  